language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

install:
  - pip install pytest codecov pytest-cov
  - pip install -e .

script:
  - pytest --cov .
  - pip install --user git+https://github.com/ptrstn/dailyblink
  - dailyblink

after_success:
  - codecov